### ISSUE TITLE
Cringe upgrades

### ISSUE THREAD

**Issue by H011up** [MrDimaseS/Ebf-BugReports#11]
Ogre Magi If you bought shard fire shield refuses to lvlup manually with ult, you need to waste skill points to lvlup your shard
Centaur Suiciderunner shard doesn't work (also can we have same thing with pudge that in doesn't amplify self damage?)
Dragon Knight shard has 4 lvl despite you can get only 3 from leveling up, fourth lvl not allowed to be upgraded
Weaver someone already said
Phoenix aghs can't be used on ally
Morphling Aghanim Doesn't exist
Spectre Aghanim Doesn't exist

**Comment by john-mayhem** [comment]
Should be filled as separate issues
