### ISSUE TITLE
The Phantom Lancer Crash

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#111]
Round 14 - Axe 17:43
Phantom Lancer used Spirit lance and Doppleganger before Axe boss Culling Blade Witch doctor, failed to killed Witch doctor. After that it Crashed. no Berserker Call, so Probably something to do with the Counter Helix or else
![plcrash](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/f6e31d42-d294-4972-8bf3-261249fd3e89)

**Comment by Pongosss** [comment]
Round 14 - Axe 17:45
Wraith King reincarnating
![Screenshot (155)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/9c604902-844c-452a-adb5-9fd4e64e0f7f)

**Comment by john-mayhem** [comment]
PLs illusions were dialed down.
