### ISSUE TITLE
Spell Amp does not get applied on veno spells

### ISSUE THREAD

**Issue by Rumoow** [MrDimaseS/Ebf-BugReports#116]
Venomancer spells seems to apply a debuff that deals dmg. Dmg numbers are fixed on the initial value and does not get increased by spell amp. dont know if that is intended or not

**Comment by Rumoow** [comment]
seems like only poison sting and gale are affected, ultimate scales

**Comment by Yahnich** [comment]
did you check the combat log

**Comment by Rumoow** [comment]
nevermind mb, combat log is accurate. jut a displaying error, thx
