### ISSUE TITLE
Zombie Round Crash

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#119]
rarely happen, but still happen in new patch.

after new patch. 09:06 - doom casted doom on 1 hp last undying. crash after round finished
![Screenshot (185)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/46d575de-7601-40aa-8dc7-8432d58de3c0)

before patch.  05:58 - crash after round finished killing small zombie from tomb (tomb already destroyed)
![Screenshot (154)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/92de6f1f-e82b-470d-bf0f-0a751643ab5a)

before patch. 06:23 - crash in the middle of round, alchemist launched charged stun
![Screenshot (171)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/2e932018-f58b-4fef-bc68-981aabf83a7b)

**Comment by Yahnich** [comment]
have not seen this in a while, reopen if happens again
