### ISSUE TITLE
Brewmaster

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#133]
Talent:
lv15, +0.5x brewup multiplier doesn't work.
lv20, +40k brewlings HP doesn't work on Primal Companion, only Primal Split. also somehow the tooltip shows wrong sum :lul:
lv25, cinder brew applies fear doesn't work

The Aghanim tooltip for 2 ultimate charges and cancel are outdated or doesn't work. Primal companion works fine.
The shard tooltip is outdated or completely wrong. only gives ultimate cancel no increase to ultimate duration.

Buff the Brewlings please :)
They all have very low attack dmg and attack spd, 0 magic resistance except for earth-ling, and all 0 spell amp :(

**Comment by Yahnich** [comment]
duplicate
