### ISSUE TITLE
No Enemy Spawning

### ISSUE THREAD

**Issue by Archa-1** [MrDimaseS/Ebf-BugReports#138]
Tinker Warp Flare bug. causing enemy to not spawn.

https://github.com/MrDimaseS/Ebf-BugReports/assets/91254843/330f062e-5ff4-4b65-a3ec-578383020382

**Comment by DionSplatt** [comment]
хотел поиграть соло чтобы протестировать героя и сборку, возникла ошибка: боссы появляются и тут же сами умирают, но опыт мне не идет, только деньги
