### ISSUE TITLE
Blade of Unity - Combo Breaker no internal cooldown

### ISSUE THREAD

**Issue by Dnarok** [MrDimaseS/Ebf-BugReports#139]
Despite listing a 60 second cooldown in the tooltip, it has no cooldown on how often it can proc.

![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/24534593/a29046f2-e22c-4f45-9c23-ae80dc037225)

**Comment by KaapaTeelb** [comment]
https://youtu.be/yWme2BI3Sno yep
