### ISSUE TITLE
1 HP only after asura sword

### ISSUE THREAD

**Issue by igormp** [MrDimaseS/Ebf-BugReports#145]
After buying asura sword on hard, I was left with 1hp no matter what, even after trying to drop it or leaving it at the stash

![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/5247904/c0a51994-f66d-4231-837c-485d1116f4f3)

**Comment by Yahnich** [comment]
closing old issues, have not seen anyone report this recently
