### ISSUE TITLE
Earth Splitter Spell Amp

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#150]
more spell amp less dmg :lul:
![Screenshot (337)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/4341f077-a4ba-4a34-aeca-7880da0689d7)
![Screenshot (338)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/83d6bcf0-dc53-4454-8018-8be1400219b4)
![Screenshot (339)](https://github.com/MrDimaseS/Ebf-BugReports/assets/130842642/89b525e2-45ff-4222-9414-8d77d8f9a017)

**Comment by Yahnich** [comment]
dupe
