### ISSUE TITLE
TB, Troll, Ursa, Viper, Weaver

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#172]
Ursa
- All Ursa skill, lvl20 talent +10 fury swipes dmg, and scepter cd vanilla

Viper
- Scepter Viper Strike doesnt work

Weaver
- Geminate Attack bonus dmg doesnt get amp by spell amp
- lvl20 talent +0.25 Swarm armor reduc, gives +0.5 armor reduc

**Comment by Yahnich** [comment]
Troll Warlord is intended, all melee heroes have a movement speed and magic resistance buff.
