### ISSUE TITLE
list of very balanced heroes

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#195]
Making the game boring pls nerf:
- Riki With Bahamut Fang full stack buff + Revenant's Brooch just delete boss. im kinda salty cause he just useless 80% of the game then he just delete boss when Bahamut Fang online

Melts Bosses, its fine if its not nerf ppl can still play the full game:
- Techies Ultimate with alot of stack, full stack with Refresher usually more than enough to delete bosses. but Boss immunity could easily prevent it, and spam-stacking a whole alot of mines in other side of the map is required to lure the bosses there and could be ruined by small bosses.

**Comment by xenob8** [comment]
Why nobody know that SD top 1 OP imho

**Comment by Pongosss** [comment]
@xenob8 top 1 OP... nope. if its his W, yes you will deal alot of dmg, but its very dependant on ur teams dmg. unless theres a specific build/mechanic/abuse that nobody know that that make him top 1 OP

**Comment by Snoresville** [comment]
@Pongosss u must have not seen the sd build in discord, i have tried it multiple times and consistently match if not outdamage necro
