### ISSUE TITLE
Necrophos still need more nerf hammer

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#197]
i read necro scepter value halfed. but still soo good. in game, 40m at mudgolem, round over after 4th split. horde round still very visible how OP necro is. ult no change?

and i think you miss sunray lvl 20 talent nerf

**Comment by Yahnich** [comment]
Reaper’s Scythe Damage Per Missing HP from 0.2/0.22/0.24/0.26/0.28/0.3 to 0.15/0.16/0.17/0.18/0.19/0.2
Reaper’s Scythe Heartstopper Aura HP Regen Bonus from 45/125/350/500/650/900 to 5/15/50/100/150/200
Reaper’s Scythe Heartstopper Aura MP Regen Bonus from 0.1/0.2/0.3/0.4/0.5/0.6 to 0.1/0.15/0.2/0.25/0.3/0.35

ult was most definitely nerfed, phoenix sun ray was nerfed indirectly thanks to talents that add +maxhp damage no longer being amped by spell amp
