### ISSUE TITLE
Arc warden bug

### ISSUE THREAD

**Issue by AloneManNikita** [MrDimaseS/Ebf-BugReports#224]
im fount bug when you up level and have clone from ult on map it get lvl and can upgrade the ult and summon other one and same for all of clones and all of them work like normal clone
![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/154319518/c5f017e6-cbb4-4450-ae4e-00586b622ba7)

**Comment by Yahnich** [comment]
dupe #168
