### ISSUE TITLE
Puck Shard and Revenant's Brooch

### ISSUE THREAD

**Issue by beats04** [MrDimaseS/Ebf-BugReports#226]
Puck Shard bonus damage doesn't seem to apply.
Revenant's Brooch upgrades are missing text.

**Comment by Yahnich** [comment]
![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/19353059/bf23da31-0b3d-43c7-b074-27fbdcb58200)
![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/19353059/ddfb2e90-55e2-4702-bab0-e76b1b312ca8)
puck shard works fine, brooch fixed
