### ISSUE TITLE
BROOCH visual bug

### ISSUE THREAD

**Issue by xenob8** [MrDimaseS/Ebf-BugReports#229]
visible dmg from brooch is incorrect (visible dmg scales with primary attribute and int, checked on sniper), but real dmg works fine and it is much more less
![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/90275969/806b2287-ad68-4a42-8e0a-91336e750802)

**Comment by Yahnich** [comment]
nothing can be done about this, combat log is always right; this is unfixable because of the way I have to interact with valve abilities and items (its not a switch i can turn off, i have to filter it out) and i cannot remove damage on hit numbers on anything
