### ISSUE TITLE
Lone Druid Spirit Link

### ISSUE THREAD

**Issue by Aoipahd** [MrDimaseS/Ebf-BugReports#243]
no work to heal bear from lone druid hit, only work on bear hit to heal lone druid
![Screenshot (628)](https://github.com/MrDimaseS/Ebf-BugReports/assets/149188367/c596e6e4-7127-4d48-9c26-defbec02dbc1)
![Screenshot (630)](https://github.com/MrDimaseS/Ebf-BugReports/assets/149188367/3bff1558-57d3-443b-be92-b6a5f6aa2069)

**Comment by Yahnich** [comment]
again that is completely normal dota behavior
