### ISSUE TITLE
Need rework to golem boss

### ISSUE THREAD

**Issue by Anim233** [MrDimaseS/Ebf-BugReports#251]
Please lower the amount of damage of the rock that golem boss is throwing at players. Because of this, the 10th wave is the hardest in the game, cause of not having enough hp + atk or lifesteal to be able to tank this rocks without full tank heroes. If you lower the damage from the rock throw skill, it'll be much better for solo and party players without teamwork

**Comment by Yahnich** [comment]
not a bug
