### ISSUE TITLE
Radiance and MKB dont scale on illu

### ISSUE THREAD

**Issue by Aoipahd** [MrDimaseS/Ebf-BugReports#256]
![Screenshot (1072)](https://github.com/MrDimaseS/Ebf-BugReports/assets/149188367/4e63da94-59b9-451f-9afd-a4aa38fec496)
![Screenshot (1074)](https://github.com/MrDimaseS/Ebf-BugReports/assets/149188367/37d5ab08-e9dd-4c95-befa-af764b634f37)

**Comment by john-mayhem** [comment]
No issue description
