### ISSUE TITLE
Marci's left level 25 talent is blank

### ISSUE THREAD

**Issue by Nemesis041** [MrDimaseS/Ebf-BugReports#266]
![image](https://github.com/MrDimaseS/Ebf-BugReports/assets/123032084/91631a44-85c5-4df5-b1f1-e6f68889fe3c)
This talent is broken regardless of chosen facet, and in the vanilla game, this is normally "Extend Unleash Duration by 6s on Kill."

**Comment by Nemesis041** [comment]
The issue is NOT fixed. This talent is still broken even on the just-now released update.

**Comment by Yahnich** [comment]
it was fixed in hero select, u are right that ingame it appeared to still be broken
fixed in live
