### ISSUE TITLE
Bane

### ISSUE THREAD

**Issue by xenob8** [MrDimaseS/Ebf-BugReports#277]
Fiend's grip has different dmg in tooltip, in UI and actual.
e.g. the tooltip shows 4,7k, UI shows 2375 and the actual dmg is 9780
also
if u stop casting Fiend's grip with scepter and illusions continue casting it, they deal ~100x less dmg. But dmg should remain the same.

**Comment by john-mayhem** [comment]
Try pressing ALT when looking at the ability - it should show the actual damage.
