### ISSUE TITLE
Clinkz is dead

### ISSUE THREAD

**Issue by H011up** [MrDimaseS/Ebf-BugReports#30]
Now when bosses don't have hp limit in ng+  clinkz can get his maximum hp in minus (screenshot carefully stolen from discord) and he will be sended in shadow realm (die) every wave reset or buyback
![image](https://user-images.githubusercontent.com/116417933/231583353-d3f9b132-ea2a-4720-8a60-168ce2848f17.png)

**Comment by 6ec2h** [comment]
The game countered the clinkz
