### ISSUE TITLE
Planeslicers and plane anvil activate at the same times 

### ISSUE THREAD

**Issue by Dovi4** [MrDimaseS/Ebf-BugReports#306]
if you activate Planeslicers, plane anvil also activate but dont give you any activity effects

**Comment by Yahnich** [comment]
intended, they share cooldowns as they're both mjollnir items

**Comment by Dovi4** [comment]
![image](https://github.com/user-attachments/assets/669b8069-8be0-4e43-9f6a-b21406161b57)
![image](https://github.com/user-attachments/assets/6e303870-3308-47d3-8f11-da37d8a44e7b)
Is it " mjollnir items"? (first pic)
I think this is MOM item and  "mjollnir items", and they activate same time. You take MOM effect, but no  mjollnir effect.

**Comment by Yahnich** [comment]
i see, will be fixed next patch
