### ISSUE TITLE
bug on centaur

### ISSUE THREAD

**Issue by KIra1UWU** [MrDimaseS/Ebf-BugReports#309]
i just play on centaur with 2 and 3 skill and when i kill first wave i see this message 
![Снимок экрана (579)](https://github.com/user-attachments/assets/ba7552b1-a9e6-4632-a5fd-68eea4080d4b)
My second skill getting no cd and wave doesn't appear (i  playing solo with no cheats)

**Comment by Yahnich** [comment]
unrelated to centaur, should be hotfixed

**Comment by Yahnich** [comment]
you can abandon the game, mmr is frozen

**Comment by KIra1UWU** [comment]
thank
