### ISSUE TITLE
Shadow Demon ultimate with aghanim cant be refreshed

### ISSUE THREAD

**Issue by Pongosss** [MrDimaseS/Ebf-BugReports#39]
in normal dota RO will refresh all 3 charges of SD ult with agh

but in EBFR either RO or t5 octarine active dont work on SD ult with agh, not even refreshing 1 charge

edit: apparently its just dont work on spell with charge in general. just tried mirana leap with RO

**Comment by john-mayhem** [comment]
RO? SD? EBFR? t5?

**Comment by Pongosss** [comment]
Refresher orb, Shadow demon, epic boss fight reborn, tier 5 octarine (otherworldly core, i forgot the name).

i think refresh just doesnt work on skill with charge (atleast mirana and shadow demon that i've tried)
