### ISSUE TITLE
WitchDoctor

### ISSUE THREAD

**Issue by 6ec2h** [MrDimaseS/Ebf-BugReports#40]
Maledist does not work on Gragon minion, although they have no immunity to magic

![20230415212618_1](https://user-images.githubusercontent.com/35076389/232247210-c2f12a43-b028-49a1-8c8c-04686a72eb32.jpg)
![20230415212643_1](https://user-images.githubusercontent.com/35076389/232247219-bd3d2d09-5e0e-498e-8559-8935dcba18ee.jpg)
![20230415212622_1](https://user-images.githubusercontent.com/35076389/232247222-39d2447d-92a3-4557-b51a-962c1eb72986.jpg)

**Comment by Yahnich** [comment]
not a bug, only affect heroes
