### ISSUE TITLE
Dragon Knight

### ISSUE THREAD

**Issue by 6ec2h** [MrDimaseS/Ebf-BugReports#47]
Fireball ability that appears with the purchase of Aghanim`s Shard, does not increase the damage when you click on the ALT, and I think this is not a visual error
![image](https://user-images.githubusercontent.com/35076389/232324725-e62a428e-bebb-4a7b-bc96-6154ab73937b.png)

**Comment by Dnarok** [comment]
It is visual, the spell is affected by spell amp.
