### ISSUE TITLE
Add the option to disable assistance !!!

### ISSUE THREAD

**Issue by hiperus0988** [MrDimaseS/Ebf-BugReports#74]
Hello, add the ability to turn off the help, tired of the "geniuses" who spoil the game for everyone, well, or that there would be an opportunity to complain about the player, this is not the first time, out of 10 games in 2-3 there are such rats ...

video: https://youtu.be/rWKjElbYIc8
Steam profile of this person: https://steamcommunity.com/profiles/76561198884433736/

**Comment by pingping-n** [comment]
upvote. same guy need to make game crash.
buy items and drop repeat with macro.
