### ISSUE TITLE
Unlimited Gold drop drop + paused wave

### ISSUE THREAD

**Issue by birdboy2396** [MrDimaseS/Ebf-BugReports#89]
were at wave 7 and once the last enemy killed, the gold dropped non stop , and the next wave is not coming. We try to suicide so that we may lose the game instead of quit directly which will deduct more mmr but it wont works, even everyone has dead, the game is still on going. and unlimited money keep on dropping

**Comment by Yahnich** [comment]
just disconnect but don't abandon; the server will automatically kill itself after about 30 seconds
issue is rectified as of latest hotfix
